require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-hc
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Max: 15
  Exclude:
    - "db/migrate/*"
Metrics/AbcSize:
  Max: 55
  Exclude:
    - "db/migrate/*"
Layout/LineLength:
  Max: 200
Metrics/BlockLength:
  Exclude:
    - "config/environments/*"
    - "db/seeds.rb"
RSpec/ContextWording:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
Hc/RailsSpecificActionName:
  Enabled: false
RSpec/NamedSubject:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/AnyInstance:
  Exclude:
    - "spec/**/*"
RSpec/LetSetup:
  Enabled: false