FROM ruby:3.2.1

RUN apt-get update -qq && apt-get install -y build-essential libpq-dev

RUN mkdir /myapp

WORKDIR /myapp

ENV RAILS_LOG_TO_STDOUT=true

COPY Gemfile /myapp/Gemfile
COPY Gemfile.lock /myapp/Gemfile.lock

RUN bundle install

COPY . /myapp

COPY entrypoint.production.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.production.sh
ENTRYPOINT ["entrypoint.production.sh"]

EXPOSE 3100
CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0", "-p", "3100"]
